### ISSUE TITLE
mod not placing torches

### ISSUE THREAD

**Issue by jerole** [dimensionsintime/TorchPlaceMod#5]
Hi!
I just added your mod to my modpack and wanted to test it. Apparently, I had no issues while loading the modpack, but when I try to place a torch, no torches are placed. Looking at the log files I see the following issues:

> [11:42:59] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$RightClickBlock@7024aa26:
java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_184429_b(Lnet/minecraft/item/ItemStack;)I
	at dimensionsintime.tpmod.event.TPModEventHandler.onPlayerInteractEvent(TPModEventHandler.java:87) ~[TPModEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1121_TPModEventHandler_onPlayerInteractEvent_RightClickBlock.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1026) [ForgeHooks.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:435) [lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) [me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) [jj.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) [jj.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[11:42:59] [Server thread/ERROR] [FML/]: Index: 39 Listeners:
[11:42:59] [Server thread/ERROR] [FML/]: 0: HIGHEST
[11:42:59] [Server thread/ERROR] [FML/]: 1: ASM: com.attributestudios.wolfarmor.event.WolfArmorPlayerEventHandler@6b0dabab onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 2: ASM: net.quetzi.morpheus.helpers.MorpheusEventHandler@aed00da bedClicked(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 3: NORMAL
[11:42:59] [Server thread/ERROR] [FML/]: 4: ASM: Block{actuallyadditions:blockLaserRelay} onBlockRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 5: ASM: net.bdew.pressure.items.HandPump$@554f377c onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 6: ASM: vazkii.quark.vanity.feature.SitInStairs@38f1f5ce onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 7: ASM: vazkii.quark.tweaks.feature.DeployLaddersDown@50760284 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 8: ASM: vazkii.quark.tweaks.feature.RemoveSnowLayers@7e8fa62 onPlayerRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 9: ASM: vazkii.quark.tweaks.feature.RightClickSignEdit@45c39aa1 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 10: ASM: class vazkii.botania.common.block.string.BlockRedStringInterceptor onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 11: ASM: vazkii.botania.common.item.material.ItemManaResource@b3b9249 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 12: ASM: class vazkii.botania.common.item.relic.ItemLokiRing onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 13: ASM: com.brandon3055.draconicevolution.handlers.DEEventHandler@38727d52 rightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 14: ASM: PegBeard.DungeonTactics.Handlers.DTEventHandler@680ba04e onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 15: ASM: org.cyclops.evilcraft.core.block.component.BlockTankComponent@3fde381e onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 16: ASM: org.cyclops.evilcraft.core.block.component.BlockTankComponent@5f5e2ddf onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 17: ASM: org.cyclops.evilcraft.core.block.component.BlockTankComponent@59e168a3 onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 18: ASM: org.cyclops.evilcraft.core.block.component.BlockTankComponent@7057042 onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 19: ASM: org.cyclops.evilcraft.core.block.component.BlockTankComponent@724f21c0 onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 20: ASM: org.cyclops.evilcraft.core.block.component.BlockTankComponent@3d21bf1f onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 21: ASM: org.cyclops.evilcraft.core.block.component.BlockTankComponent@1ac62e8f onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 22: ASM: Block{null} onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 23: ASM: org.cyclops.evilcraft.item.PoisonBottle@6aa0e0af onPoisonRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 24: ASM: com.feed_the_beast.ftbu.handlers.FTBUPlayerEventHandler@567988ac onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 25: ASM: mca.core.forge.EventHooksForge@370100e1 rightClickBlockEventHandler(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 26: ASM: mods.railcraft.common.carts.MinecartHooks@75897d0f onItemUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 27: ASM: Block{null} onRightClicked(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 28: ASM: Block{null} onRightClicked(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 29: ASM: hellfirepvp.astralsorcery.common.event.listener.EventHandlerServer@3f2ce8ef onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 30: ASM: mod.chiselsandbits.events.EventPlayerInteract@f71dcc6 interaction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 31: ASM: mcmultipart.item.PartPlacementWrapper@15e39c0 onPlayerRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 32: ASM: mcmultipart.item.PartPlacementWrapper@40f8944b onPlayerRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 33: ASM: com.enderio.core.common.handlers.RightClickCropHandler@43b1862f handleCropRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 34: ASM: shetiphian.multistorage.common.misc.EventHandler@7920c6bb playerRightClickBlockEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 35: ASM: com.jaquadro.minecraft.storagedrawers.core.CommonProxy@643582ff playerRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 36: ASM: mcjty.rftoolsdim.ForgeEventHandlers@2755090 onPlayerRightClickEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 37: ASM: class thebetweenlands.common.handler.LocationHandler onBlockRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 38: ASM: class thebetweenlands.common.handler.OverworldItemHandler onUseItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 39: ASM: class dimensionsintime.tpmod.event.TPModEventHandler onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 40: ASM: slimeknights.tconstruct.tools.ToolEvents@1e842260 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 41: ASM: WayofTime.bloodmagic.util.handler.event.GenericHandler@f271bee onPlayerClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[11:42:59] [Server thread/ERROR] [FML/]: 42: ASM: WayofTime.bloodmagic.util.handler.event.LivingArmourHandler@64c5057c onPlayerClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[11:42:59] [Server thread/ERROR] [FML/]: 43: ASM: lumien.randomthings.handler.RTEventHandler@17a72ec9 playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[11:42:59] [Server thread/ERROR] [FML/]: 44: ASM: INSTANCE onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[11:42:59] [Server thread/ERROR] [FML/]: 45: ASM: romelo333.notenoughwands.ForgeEventHandlers@7d830822 onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[11:42:59] [Server thread/ERROR] [FML/]: 46: ASM: mcjty.rftools.ForgeEventHandlers@24ef68d8 onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[11:42:59] [Server thread/ERROR] [FML/]: 47: ASM: class thebetweenlands.common.handler.ItemEquipmentHandler onItemUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[11:42:59] [Server thread/ERROR] [FML/]: 48: ASM: class thebetweenlands.common.handler.PuppetHandler onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[11:42:59] [Server thread/ERROR] [FML/]: 49: ASM: treechopper.proxy.ServerProxy@3a8354b2 interactTree(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[11:42:59] [Server thread/ERROR] [FML/]: 50: LOWEST
[11:42:59] [Server thread/ERROR] [FML/]: 51: ASM: hellfirepvp.astralsorcery.common.event.listener.EventHandlerServer@3f2ce8ef onRightClickLast(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/ERROR] [FML/]: 52: ASM: elec332.core.main.ElecCore$1@4d44b10a onItemRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:42:59] [Server thread/DEBUG] [FML/]: The world 20a17d1d (world) may have leaked: seen 130 times.

> [11:42:59] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_184429_b(Lnet/minecraft/item/ItemStack;)I
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_184429_b(Lnet/minecraft/item/ItemStack;)I
	at dimensionsintime.tpmod.event.TPModEventHandler.onPlayerInteractEvent(TPModEventHandler.java:87) ~[TPModEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1121_TPModEventHandler_onPlayerInteractEvent_RightClickBlock.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1026) ~[ForgeHooks.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:435) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more

**Comment by dimensionsintime** [comment]
I see what it is, there's a bit of code that should be sided client but it's being run on the server side. Will get a fix out as quick as I can (out of the house today).

**Comment by dimensionsintime** [comment]
New release 0.7 moves inventory check to client side, which should eliminate problem. Also added a configuration set up so you can enable/disable the mod's functionality in the config file. Let me know if this fixes your issue.

**Comment by jerole** [comment]
That was fast, I will test it this evening after work and let you know if it works.

**Comment by jerole** [comment]
I just tried the new update, but unfortunately it is still nor working. Now I see the following error in the logs:

> [18:25:02] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$RightClickBlock@39aab70e:
java.lang.StackOverflowError
	at dimensionsintime.tpmod.proxy.ServerProxy.getSlotFor(ServerProxy.java:19) ~[ServerProxy.class:?]
	at dimensionsintime.tpmod.proxy.ServerProxy.getSlotFor(ServerProxy.java:19) ~[ServerProxy.class:?]
	at dimensionsintime.tpmod.proxy.ServerProxy.getSlotFor(ServerProxy.java:19) ~[ServerProxy.class:?]
        . 
        .  
        .
	at dimensionsintime.tpmod.proxy.ServerProxy.getSlotFor(ServerProxy.java:19) ~[ServerProxy.class:?]
[18:25:03] [Server thread/ERROR] [FML/]: Index: 39 Listeners:
[18:25:03] [Server thread/ERROR] [FML/]: 0: HIGHEST
[18:25:03] [Server thread/ERROR] [FML/]: 1: ASM: com.attributestudios.wolfarmor.event.WolfArmorPlayerEventHandler@3448fab1 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 2: ASM: net.quetzi.morpheus.helpers.MorpheusEventHandler@39e69ce5 bedClicked(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 3: NORMAL
[18:25:03] [Server thread/ERROR] [FML/]: 4: ASM: Block{actuallyadditions:blockLaserRelay} onBlockRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 5: ASM: net.bdew.pressure.items.HandPump$@7a93a048 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 6: ASM: vazkii.quark.vanity.feature.SitInStairs@2719b591 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 7: ASM: vazkii.quark.tweaks.feature.DeployLaddersDown@6c5bbb17 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 8: ASM: vazkii.quark.tweaks.feature.RemoveSnowLayers@2ba17edc onPlayerRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 9: ASM: vazkii.quark.tweaks.feature.RightClickSignEdit@7595f4ff onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 10: ASM: class vazkii.botania.common.block.string.BlockRedStringInterceptor onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 11: ASM: vazkii.botania.common.item.material.ItemManaResource@7c3d5612 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 12: ASM: class vazkii.botania.common.item.relic.ItemLokiRing onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 13: ASM: com.brandon3055.draconicevolution.handlers.DEEventHandler@c92364b rightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 14: ASM: PegBeard.DungeonTactics.Handlers.DTEventHandler@61d796fb onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 15: ASM: org.cyclops.evilcraft.core.block.component.BlockTankComponent@174abf3f onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 16: ASM: org.cyclops.evilcraft.core.block.component.BlockTankComponent@77b2f19e onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 17: ASM: org.cyclops.evilcraft.core.block.component.BlockTankComponent@7bd29e92 onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 18: ASM: org.cyclops.evilcraft.core.block.component.BlockTankComponent@29b107e onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 19: ASM: org.cyclops.evilcraft.core.block.component.BlockTankComponent@28b0e715 onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 20: ASM: org.cyclops.evilcraft.core.block.component.BlockTankComponent@347091df onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 21: ASM: org.cyclops.evilcraft.core.block.component.BlockTankComponent@6149f781 onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 22: ASM: Block{null} onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 23: ASM: org.cyclops.evilcraft.item.PoisonBottle@416bc51d onPoisonRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 24: ASM: com.feed_the_beast.ftbu.handlers.FTBUPlayerEventHandler@52e3d18d onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 25: ASM: mca.core.forge.EventHooksForge@726f9d43 rightClickBlockEventHandler(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 26: ASM: mods.railcraft.common.carts.MinecartHooks@6d199a38 onItemUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 27: ASM: Block{null} onRightClicked(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 28: ASM: Block{null} onRightClicked(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 29: ASM: hellfirepvp.astralsorcery.common.event.listener.EventHandlerServer@4e56ffa2 onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 30: ASM: mod.chiselsandbits.events.EventPlayerInteract@74450c2e interaction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 31: ASM: mcmultipart.item.PartPlacementWrapper@10fa3dd6 onPlayerRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 32: ASM: mcmultipart.item.PartPlacementWrapper@4836ac5c onPlayerRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 33: ASM: com.enderio.core.common.handlers.RightClickCropHandler@59d0aaed handleCropRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 34: ASM: shetiphian.multistorage.common.misc.EventHandler@24e159dd playerRightClickBlockEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 35: ASM: com.jaquadro.minecraft.storagedrawers.core.CommonProxy@42dcebeb playerRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 36: ASM: mcjty.rftoolsdim.ForgeEventHandlers@2eacc3a5 onPlayerRightClickEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 37: ASM: class thebetweenlands.common.handler.LocationHandler onBlockRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 38: ASM: class thebetweenlands.common.handler.OverworldItemHandler onUseItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 39: ASM: class dimensionsintime.tpmod.handlers.TPModEventHandler onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 40: ASM: slimeknights.tconstruct.tools.ToolEvents@5cae081f onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 41: ASM: WayofTime.bloodmagic.util.handler.event.GenericHandler@1bbd0d40 onPlayerClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:25:03] [Server thread/ERROR] [FML/]: 42: ASM: WayofTime.bloodmagic.util.handler.event.LivingArmourHandler@25b3f2c5 onPlayerClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:25:03] [Server thread/ERROR] [FML/]: 43: ASM: lumien.randomthings.handler.RTEventHandler@21045bfd playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:25:03] [Server thread/ERROR] [FML/]: 44: ASM: INSTANCE onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:25:03] [Server thread/ERROR] [FML/]: 45: ASM: romelo333.notenoughwands.ForgeEventHandlers@323e198f onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:25:03] [Server thread/ERROR] [FML/]: 46: ASM: mcjty.rftools.ForgeEventHandlers@16858ec9 onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:25:03] [Server thread/ERROR] [FML/]: 47: ASM: class thebetweenlands.common.handler.ItemEquipmentHandler onItemUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:25:03] [Server thread/ERROR] [FML/]: 48: ASM: class thebetweenlands.common.handler.PuppetHandler onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:25:03] [Server thread/ERROR] [FML/]: 49: ASM: treechopper.proxy.ServerProxy@225a9516 interactTree(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:25:03] [Server thread/ERROR] [FML/]: 50: LOWEST
[18:25:03] [Server thread/ERROR] [FML/]: 51: ASM: hellfirepvp.astralsorcery.common.event.listener.EventHandlerServer@4e56ffa2 onRightClickLast(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:25:03] [Server thread/ERROR] [FML/]: 52: ASM: elec332.core.main.ElecCore$1@4f298c0d onItemRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V

> [18:25:03] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.StackOverflowError
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.StackOverflowError
	at dimensionsintime.tpmod.proxy.ServerProxy.getSlotFor(ServerProxy.java:19) ~[ServerProxy.class:?]
	at dimensionsintime.tpmod.proxy.ServerProxy.getSlotFor(ServerProxy.java:19) ~[ServerProxy.class:?]
	....

**Comment by dimensionsintime** [comment]
Blargh! Should have paid closer attention, getSlotFor() is sided client as well. Working...

**Comment by dimensionsintime** [comment]
Ok, this time I wrote my own routine to search through player's inventory and find the slot with torches, which should eliminate the bug.

@jerole thanks for helping me squash this. If I can ask, what version of 1.10.2 forge are you running?

**Comment by jerole** [comment]
I am running forge 12.18.3.2185

**Comment by jerole** [comment]
Just tested the new update and it works! Thanks a lot :)

**Comment by dimensionsintime** [comment]
Awesome! Thanks for the version number, that's the one I used to build the mod but wanted to be sure. Glad it works now, marking this fixed.
